# default configuration, override in config/local.toml or with env vars

# application name used for logging and service namespace
name = 'greymass-revoter'

# eosio chain to use, jungle default
eosio_chain = 'e70aaab8997e1dfce58fbfac80cbbb8fecec7b99cf982a9444273cbc64c41473'

# eosio rpc node used to transact
eosio_node = 'https://jungleapi.eossweden.se'

# permission name to look for
eosio_perm = 'vote'

# signing private key, required
# eosio_key = '5contractspecifickeynotactiveplz'

# how often to check if accounts need votes refreshed
update_interval = 600 # seconds

# logging output, can be repeated
[[log]]
level = 'debug'
out = 'stdout' # path or stdout/err
